[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "packutil"
version = "1.0.0"
description = "Shared utilities for PackIt plugin"
requires-python = "==3.11"

[tool.setuptools]
packages = ["packutil"]

[tool.setuptools.package-dir]
packutil = "package"
